//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarId { get; set; }
        public int CarTypeId { get; set; }
        public int Mileage { get; set; }
        public string PictureUrl { get; set; }
        public bool FitForRental { get; set; }
        public bool Available { get; set; }
        public string CarNumber { get; set; }
        public int BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual CarType CarType { get; set; }
    }
}
